server:
    port: 8081

spring:
    application:
        name: provider-8081

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cloud_test?useUnicode=true&useSSL=false&characterEncoding=utf8
        username: root
        password: "123456"

    jpa:
        generate-ddl: true
        # 展示运行的SQL
        show-sql: true
        hibernate:
            ddl-auto: none


# 配置日志
logging:
    # 控制台日志的输出格式
    pattern:
        console: level-%level %msg%n
    level:
        # 控制spring boot启动时显示的日志级别
        root: info
        # 控制hibernate运行时的日志级别
        org.hibernate: info
        # 控制自己的代码运行时显示的日志级别
        com.cloud: debug

        # 在show-sql为true时显示SQL中的动态参数值
        org.hibernate.type.descriptor.sql.BasicBinder: trace
        # 在show-sql为true时显示查询结果
        org.hibernate.type.descriptor.sql.BasicExtractor: trace




