server:
    port: 8004

spring:
    application:
        name: consumer-nacos-8004
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8868
                username: nacos
                password: nacos
                #               默认为 true - 设置为false 则不向nacos中注册
                enabled: true
                #默认为true 表示临时实例
                ephemeral: true

        openfeign:
            client:
                config:
                 #全局设置
                  default:
                      # 连接超时 网络连接超时
                      connect-timeout: 1
                      # 被调用方业务处理超时
                      read-timeout: 1
                  # 局部设置 针对某个FeignName
                  provider-8082:
                      connect-timeout: 10
                      read-timeout: 20
            # 请求压缩 - 看官网学习配置
            compression:
                request:
                    enabled: true
                    #压缩阈值 - 大于进行压缩
                    min-request-size: 1024

                response:
                    enabled: true

            # 默认使用httpClient - 


















